# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='uploads/image_none.png', upload_to='uploads/'),
        ),
    ]
