# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-25 07:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_id_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='id_category',
            new_name='category',
        ),
    ]
